# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_settings_hide_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(choices=[('grey_boxes', 'Grey Boxes'), ('light', 'Light Glow'), ('dark', 'Dark Dusk')], default='light', max_length=10),
        ),
    ]
