# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170915_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='no_analytics',
            field=models.BooleanField(default=True),
        ),
    ]
