# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20150902_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[(b'white', b'White'), (b'red', b'Red'), (b'orange', b'Orange'), (b'yellow', b'Yellow'), (b'green', b'Green'), (b'cyan', b'Cyan'), (b'blue', b'Blue'), (b'magenta', b'Magenta'), (b'darkred', b'Dark Red'), (b'darkgreen', b'Dark Green'), (b'darkblue', b'Dark Blue'), (b'black', b'Black')], default=b'white', max_length=20),
        ),
    ]
