# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20150902_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('magenta', 'Magenta'), ('darkred', 'Dark Red'), ('darkgreen', 'Dark Green'), ('darkblue', 'Dark Blue'), ('black', 'Black')], default='white', max_length=20),
        ),
    ]
