# Generated by Django 2.2.28 on 2023-08-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20170918_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='colour',
            field=models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('cyan', 'Cyan'), ('blue', 'Blue'), ('magenta', 'Magenta'), ('darkred', 'Dark Red'), ('darkgreen', 'Dark Green'), ('darkblue', 'Dark Blue'), ('black', 'Black')], default='white', max_length=20),
        ),
    ]
